### ISSUE TITLE
Thanks for using Truegit! Found the logo issue you might want to fix

### ISSUE THREAD

**Issue by quant-daddy** [algoexpt/randomwalks#2]
The logo file, and in fact any asset file that you want to reference, must be in the blog folder. In the truegit.yaml, you are using `blog` folder as the root folder for your blog so the logo.png file must be inside the folder for it to show. Any file outside the blog folder is ignored (except of course the truegit.yaml which must always be in the root folder). Does that make sense? 

Really cool blog BTW!

**Comment by algoexpt** [comment]
That makes sense and it worked. Thanks!
